name: CI Test Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # python version 3.9 installations
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: All Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pandas sqlite3

     
      - name: Unit Tests Run
        run: |
          python3 -m unittest project/test.py
