name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: List repository files (debug)
      run: ls -R

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
        pip install pandas
        pip install sqlalchemy
        pip install requests
      

    - name: Run Tests
      run: pytest project/test.py
